# Generated by Django 2.2.7 on 2019-11-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='state',
            field=models.CharField(choices=[('lagos', 'Lagos'), ('imo', 'Imo'), ('abuja', 'Abuja'), ('port-hacourt', 'Port-hacourt')], default='Lagos', max_length=50),
        ),
        migrations.AddField(
            model_name='review',
            name='unlike',
            field=models.IntegerField(default=0),
        ),
    ]
